# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='profile.proto',
  package='serve',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rprofile.proto\x12\x05serve\"%\n\x12UserProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"Z\n\x13UserProfileResponse\x12\t\n\x01\x66\x18\x01 \x01(\t\x12\t\n\x01h\x18\x02 \x01(\t\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\r\n\x05total\x18\x04 \x01(\x05\x12\x10\n\x08hratings\x18\x05 \x01(\x01\"\'\n\x13MovieProfileRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\x03\"W\n\x14MovieProfileResponse\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\x12\n\ntotal_time\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0e\n\x06genres\x18\x04 \x01(\t2\xab\x01\n\x0eProfileService\x12J\n\x0f\x43\x61llUserProfile\x12\x19.serve.UserProfileRequest\x1a\x1a.serve.UserProfileResponse\"\x00\x12M\n\x10\x43\x61llMovieProfile\x12\x1a.serve.MovieProfileRequest\x1a\x1b.serve.MovieProfileResponse\"\x00\x62\x06proto3'
)




_USERPROFILEREQUEST = _descriptor.Descriptor(
  name='UserProfileRequest',
  full_name='serve.UserProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='serve.UserProfileRequest.user_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=61,
)


_USERPROFILERESPONSE = _descriptor.Descriptor(
  name='UserProfileResponse',
  full_name='serve.UserProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='f', full_name='serve.UserProfileResponse.f', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='h', full_name='serve.UserProfileResponse.h', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='serve.UserProfileResponse.high', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='serve.UserProfileResponse.total', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hratings', full_name='serve.UserProfileResponse.hratings', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=153,
)


_MOVIEPROFILEREQUEST = _descriptor.Descriptor(
  name='MovieProfileRequest',
  full_name='serve.MovieProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_id', full_name='serve.MovieProfileRequest.movie_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=194,
)


_MOVIEPROFILERESPONSE = _descriptor.Descriptor(
  name='MovieProfileResponse',
  full_name='serve.MovieProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='serve.MovieProfileResponse.mean', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_time', full_name='serve.MovieProfileResponse.total_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='serve.MovieProfileResponse.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genres', full_name='serve.MovieProfileResponse.genres', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=283,
)

DESCRIPTOR.message_types_by_name['UserProfileRequest'] = _USERPROFILEREQUEST
DESCRIPTOR.message_types_by_name['UserProfileResponse'] = _USERPROFILERESPONSE
DESCRIPTOR.message_types_by_name['MovieProfileRequest'] = _MOVIEPROFILEREQUEST
DESCRIPTOR.message_types_by_name['MovieProfileResponse'] = _MOVIEPROFILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserProfileRequest = _reflection.GeneratedProtocolMessageType('UserProfileRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILEREQUEST,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:serve.UserProfileRequest)
  })
_sym_db.RegisterMessage(UserProfileRequest)

UserProfileResponse = _reflection.GeneratedProtocolMessageType('UserProfileResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILERESPONSE,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:serve.UserProfileResponse)
  })
_sym_db.RegisterMessage(UserProfileResponse)

MovieProfileRequest = _reflection.GeneratedProtocolMessageType('MovieProfileRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEPROFILEREQUEST,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:serve.MovieProfileRequest)
  })
_sym_db.RegisterMessage(MovieProfileRequest)

MovieProfileResponse = _reflection.GeneratedProtocolMessageType('MovieProfileResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEPROFILERESPONSE,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:serve.MovieProfileResponse)
  })
_sym_db.RegisterMessage(MovieProfileResponse)



_PROFILESERVICE = _descriptor.ServiceDescriptor(
  name='ProfileService',
  full_name='serve.ProfileService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=286,
  serialized_end=457,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallUserProfile',
    full_name='serve.ProfileService.CallUserProfile',
    index=0,
    containing_service=None,
    input_type=_USERPROFILEREQUEST,
    output_type=_USERPROFILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CallMovieProfile',
    full_name='serve.ProfileService.CallMovieProfile',
    index=1,
    containing_service=None,
    input_type=_MOVIEPROFILEREQUEST,
    output_type=_MOVIEPROFILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROFILESERVICE)

DESCRIPTOR.services_by_name['ProfileService'] = _PROFILESERVICE

# @@protoc_insertion_point(module_scope)
