# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import profile_pb2 as profile__pb2


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallUserProfile = channel.unary_unary(
                '/serve.ProfileService/CallUserProfile',
                request_serializer=profile__pb2.UserProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.UserProfileResponse.FromString,
                )
        self.CallMovieProfile = channel.unary_unary(
                '/serve.ProfileService/CallMovieProfile',
                request_serializer=profile__pb2.MovieProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.MovieProfileResponse.FromString,
                )


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallMovieProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CallUserProfile,
                    request_deserializer=profile__pb2.UserProfileRequest.FromString,
                    response_serializer=profile__pb2.UserProfileResponse.SerializeToString,
            ),
            'CallMovieProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CallMovieProfile,
                    request_deserializer=profile__pb2.MovieProfileRequest.FromString,
                    response_serializer=profile__pb2.MovieProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serve.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.ProfileService/CallUserProfile',
            profile__pb2.UserProfileRequest.SerializeToString,
            profile__pb2.UserProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallMovieProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.ProfileService/CallMovieProfile',
            profile__pb2.MovieProfileRequest.SerializeToString,
            profile__pb2.MovieProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
