# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serve_pb2 as serve__pb2


class MainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/serve.MainService/Call',
                request_serializer=serve__pb2.MainRequest.SerializeToString,
                response_deserializer=serve__pb2.ScoreResponse.FromString,
                )


class MainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=serve__pb2.MainRequest.FromString,
                    response_serializer=serve__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serve.MainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.MainService/Call',
            serve__pb2.MainRequest.SerializeToString,
            serve__pb2.ScoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallUserProfile = channel.unary_unary(
                '/serve.ProfileService/CallUserProfile',
                request_serializer=serve__pb2.UserProfileRequest.SerializeToString,
                response_deserializer=serve__pb2.UserProfileResponse.FromString,
                )
        self.CallMovieProfile = channel.unary_unary(
                '/serve.ProfileService/CallMovieProfile',
                request_serializer=serve__pb2.MovieProfileRequest.SerializeToString,
                response_deserializer=serve__pb2.MovieProfileResponse.FromString,
                )


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallMovieProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CallUserProfile,
                    request_deserializer=serve__pb2.UserProfileRequest.FromString,
                    response_serializer=serve__pb2.UserProfileResponse.SerializeToString,
            ),
            'CallMovieProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CallMovieProfile,
                    request_deserializer=serve__pb2.MovieProfileRequest.FromString,
                    response_serializer=serve__pb2.MovieProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serve.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.ProfileService/CallUserProfile',
            serve__pb2.UserProfileRequest.SerializeToString,
            serve__pb2.UserProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallMovieProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.ProfileService/CallMovieProfile',
            serve__pb2.MovieProfileRequest.SerializeToString,
            serve__pb2.MovieProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ReCallServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallReCall = channel.unary_unary(
                '/serve.ReCallService/CallReCall',
                request_serializer=serve__pb2.ReCallRequest.SerializeToString,
                response_deserializer=serve__pb2.ReCallResponse.FromString,
                )


class ReCallServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallReCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReCallServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallReCall': grpc.unary_unary_rpc_method_handler(
                    servicer.CallReCall,
                    request_deserializer=serve__pb2.ReCallRequest.FromString,
                    response_serializer=serve__pb2.ReCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serve.ReCallService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReCallService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallReCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.ReCallService/CallReCall',
            serve__pb2.ReCallRequest.SerializeToString,
            serve__pb2.ReCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ScoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallScore = channel.unary_unary(
                '/serve.ScoreService/CallScore',
                request_serializer=serve__pb2.ScoreRequest.SerializeToString,
                response_deserializer=serve__pb2.ScoreResponse.FromString,
                )


class ScoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CallScore,
                    request_deserializer=serve__pb2.ScoreRequest.FromString,
                    response_serializer=serve__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serve.ScoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.ScoreService/CallScore',
            serve__pb2.ScoreRequest.SerializeToString,
            serve__pb2.ScoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
