# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import score_pb2 as score__pb2


class ScoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallScore = channel.unary_unary(
                '/serve.ScoreService/CallScore',
                request_serializer=score__pb2.ScoreRequest.SerializeToString,
                response_deserializer=score__pb2.ScoreResponse.FromString,
                )


class ScoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CallScore,
                    request_deserializer=score__pb2.ScoreRequest.FromString,
                    response_serializer=score__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serve.ScoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serve.ScoreService/CallScore',
            score__pb2.ScoreRequest.SerializeToString,
            score__pb2.ScoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
