# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='score.proto',
  package='serve',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bscore.proto\x12\x05serve\"\x8c\x01\n\x0cScoreRequest\x12\x15\n\rmovie_id_list\x18\x01 \x03(\x03\x12\x30\n\x0cuser_profile\x18\x02 \x01(\x0b\x32\x1a.serve.UserProfileResponse\x12\x33\n\x0emovie_profiles\x18\x03 \x03(\x0b\x32\x1b.serve.MovieProfileResponse\"-\n\rScoreResponse\x12\x1c\n\x06scores\x18\x01 \x03(\x0b\x32\x0c.serve.Score\"7\n\x05Score\x12\x10\n\x08movie_id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\"Z\n\x13UserProfileResponse\x12\t\n\x01\x66\x18\x01 \x01(\t\x12\t\n\x01h\x18\x02 \x01(\t\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\r\n\x05total\x18\x04 \x01(\x05\x12\x10\n\x08hratings\x18\x05 \x01(\x01\"W\n\x14MovieProfileResponse\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\x12\n\ntotal_time\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0e\n\x06genres\x18\x04 \x01(\t2H\n\x0cScoreService\x12\x38\n\tCallScore\x12\x13.serve.ScoreRequest\x1a\x14.serve.ScoreResponse\"\x00\x62\x06proto3'
)




_SCOREREQUEST = _descriptor.Descriptor(
  name='ScoreRequest',
  full_name='serve.ScoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_id_list', full_name='serve.ScoreRequest.movie_id_list', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_profile', full_name='serve.ScoreRequest.user_profile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movie_profiles', full_name='serve.ScoreRequest.movie_profiles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=163,
)


_SCORERESPONSE = _descriptor.Descriptor(
  name='ScoreResponse',
  full_name='serve.ScoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scores', full_name='serve.ScoreResponse.scores', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=210,
)


_SCORE = _descriptor.Descriptor(
  name='Score',
  full_name='serve.Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_id', full_name='serve.Score.movie_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='serve.Score.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='serve.Score.score', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=267,
)


_USERPROFILERESPONSE = _descriptor.Descriptor(
  name='UserProfileResponse',
  full_name='serve.UserProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='f', full_name='serve.UserProfileResponse.f', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='h', full_name='serve.UserProfileResponse.h', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='serve.UserProfileResponse.high', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='serve.UserProfileResponse.total', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hratings', full_name='serve.UserProfileResponse.hratings', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=359,
)


_MOVIEPROFILERESPONSE = _descriptor.Descriptor(
  name='MovieProfileResponse',
  full_name='serve.MovieProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='serve.MovieProfileResponse.mean', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_time', full_name='serve.MovieProfileResponse.total_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='serve.MovieProfileResponse.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genres', full_name='serve.MovieProfileResponse.genres', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=448,
)

_SCOREREQUEST.fields_by_name['user_profile'].message_type = _USERPROFILERESPONSE
_SCOREREQUEST.fields_by_name['movie_profiles'].message_type = _MOVIEPROFILERESPONSE
_SCORERESPONSE.fields_by_name['scores'].message_type = _SCORE
DESCRIPTOR.message_types_by_name['ScoreRequest'] = _SCOREREQUEST
DESCRIPTOR.message_types_by_name['ScoreResponse'] = _SCORERESPONSE
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
DESCRIPTOR.message_types_by_name['UserProfileResponse'] = _USERPROFILERESPONSE
DESCRIPTOR.message_types_by_name['MovieProfileResponse'] = _MOVIEPROFILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScoreRequest = _reflection.GeneratedProtocolMessageType('ScoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCOREREQUEST,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:serve.ScoreRequest)
  })
_sym_db.RegisterMessage(ScoreRequest)

ScoreResponse = _reflection.GeneratedProtocolMessageType('ScoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCORERESPONSE,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:serve.ScoreResponse)
  })
_sym_db.RegisterMessage(ScoreResponse)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), {
  'DESCRIPTOR' : _SCORE,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:serve.Score)
  })
_sym_db.RegisterMessage(Score)

UserProfileResponse = _reflection.GeneratedProtocolMessageType('UserProfileResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILERESPONSE,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:serve.UserProfileResponse)
  })
_sym_db.RegisterMessage(UserProfileResponse)

MovieProfileResponse = _reflection.GeneratedProtocolMessageType('MovieProfileResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEPROFILERESPONSE,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:serve.MovieProfileResponse)
  })
_sym_db.RegisterMessage(MovieProfileResponse)



_SCORESERVICE = _descriptor.ServiceDescriptor(
  name='ScoreService',
  full_name='serve.ScoreService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=450,
  serialized_end=522,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallScore',
    full_name='serve.ScoreService.CallScore',
    index=0,
    containing_service=None,
    input_type=_SCOREREQUEST,
    output_type=_SCORERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCORESERVICE)

DESCRIPTOR.services_by_name['ScoreService'] = _SCORESERVICE

# @@protoc_insertion_point(module_scope)
